version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:17

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # catch build-time errors (if any)
      - run: npm run build:lib

      - store_artifacts:
           path: ./dist/lib/VueMoveable.umd.min.js
           destination: VueMoveable.umd.min.js

      - run:
          name: Run code-style check
          command: npm run lint -- --format junit -o /tmp/test-results/code-style-test-results.xml

      - store_test_results:
          path: /tmp/test-results
